import { Game } from '@/types';

export const seedGames: Game[] = [
  {
    id: 'online-tic-tac-toe',
    title: 'Online Tic Tac Toe',
    shortDescription: 'Create or join a room and play Tic Tac Toe online.',
    fullDescription: 'Challenge your friends to a game of Tic Tac Toe! Create a room or join with a room code. Real-time multiplayer gameplay with Firebase synchronization.',
    thumbnail: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=300&fit=crop',
    banner: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=1200&h=400&fit=crop',
    category: 'Strategy',
    difficulty: 'Easy',
    tags: ['multiplayer', 'strategy', 'classic'],
    featured: true,
    multiplayer: true,
    authRequired: true,
    minPlayers: 2,
    maxPlayers: 2,
    status: 'live',
    playCount: 0,
  },
  {
    id: 'online-rock-paper-scissors',
    title: 'Online Rock Paper Scissors',
    shortDescription: 'Challenge another player in a quick online match.',
    fullDescription: 'Play the classic game of Rock Paper Scissors against another authenticated player online. Quick matches, real-time results, and competitive fun!',
    thumbnail: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop',
    banner: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=1200&h=400&fit=crop',
    category: 'Battle',
    difficulty: 'Easy',
    tags: ['multiplayer', 'quick', 'classic'],
    featured: true,
    multiplayer: true,
    authRequired: true,
    minPlayers: 2,
    maxPlayers: 2,
    status: 'beta',
    playCount: 0,
  },
  {
    id: 'online-quiz-battle',
    title: 'Online Quiz Battle',
    shortDescription: 'Compete with another authenticated player in a live quiz match.',
    fullDescription: 'Test your knowledge against other players in live quiz battles. Answer questions faster than your opponents to win! Real-time competition with authenticated players only.',
    thumbnail: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop',
    banner: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=400&fit=crop',
    category: 'Trivia',
    difficulty: 'Medium',
    tags: ['multiplayer', 'quiz', 'battle'],
    featured: true,
    multiplayer: true,
    authRequired: true,
    minPlayers: 2,
    maxPlayers: 2,
    status: 'beta',
    playCount: 0,
  },
  {
    id: 'typing-race',
    title: 'Typing Race',
    shortDescription: 'Race another logged-in player by typing faster and more accurately.',
    fullDescription: 'Compete in real-time typing races against other authenticated players. Type the same passage faster and more accurately than your opponent to win!',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop',
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=400&fit=crop',
    category: 'Speed',
    difficulty: 'Medium',
    tags: ['multiplayer', 'typing', 'speed', 'race'],
    featured: false,
    multiplayer: true,
    authRequired: true,
    minPlayers: 2,
    maxPlayers: 4,
    status: 'beta',
    playCount: 0,
  },
  {
    id: 'reaction-battle',
    title: 'Reaction Battle',
    shortDescription: 'Compete to react faster than another player.',
    fullDescription: 'Test your reaction speed against another authenticated player in real-time. See who can click faster when the signal appears. Fast-paced competitive fun!',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&h=400&fit=crop',
    category: 'Speed',
    difficulty: 'Easy',
    tags: ['multiplayer', 'reaction', 'speed', 'battle'],
    featured: false,
    multiplayer: true,
    authRequired: true,
    minPlayers: 2,
    maxPlayers: 2,
    status: 'beta',
    playCount: 0,
  },
];
